name: DEV - Build/Publish AML Managed Online Endpoint

on:

  workflow_dispatch:
  
  push:
    branches:
      - dev
    paths:
      - 'managed-online-endpoint/src/**'
      - 'managed-online-endpoint/pipeline_build.py'

jobs:
  build-publish:
    uses: ./.github/workflows/aml-build-managed-online-endpoint-BASE.yml
    with:
      environment: dev
      
    secrets: 
      AZURE_CREDENTIALS: ${{ secrets.SP_IAASBXARMMLWUW2033 }}
