name: AzureML Build Batch Pipeline Endpoint BASE

# Controls when the workflow will run
on:
  # Reusable workflow.
  workflow_call:
    inputs:
      RESOURCEGROUP:
        required: true
        type: string
        description: The name of the Azure Resource Group
      LOCATION:
        required: true
        type: string
        description: The region of the Azure Resource Group
      WORKSPACE:
        required: true
        type: string
        description: The name of the AzureML Workspace   
      DEFAULTCLUSTER:
        required: true
        type: string
        description: The defualt compute cluster path
      ADGROUP:
        required: true
        type: string
        description: Active Directory group of the AzureML Workspace 
      DEFAULTSTORAGE:
        required: true
        type: string
        description: Default AzureML Storage name
      SUBSCRIPTION:
        required: true
        type: string
        description: Subscription of the Active Directory Group
      REPOPATH:
        required: true
        type: string
        description: Branch to Checkout
    secrets:
      azure-sp-credential:
        required: true
        description: AzureML Service Principal Credential
jobs:
  build-publish-aml-endpoint:
    runs-on: ubuntu-latest
    steps:
    
    - name: Grab the Branch for the Workflow
      run: |
          echo Github reference name $GITHUB_REF_NAME
          echo Github reference name $GITHUB_REF
          
    - name: Checkout Branch
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.REPOPATH }}

    - name: Login to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.azure-sp-credential }}

    - name: Whitelist the IP Address of the Github Runner
      run: bash whitelist-ip-add.sh ${{ inputs.DEFAULTSTORAGE }} ${{ inputs.SUBSCRIPTION }} ${{ inputs.RESOURCEGROUP }} ${{ inputs.REPOPATH }}
      working-directory: Resources/AzureML/cli
      continue-on-error: false
        
    - name: Setup AZ ML CLI Extension and Default Workspace
      run: bash setup.sh ${{ inputs.RESOURCEGROUP }} ${{ inputs.LOCATION }} ${{ inputs.WORKSPACE }}
      working-directory: Resources/AzureML/cli
      continue-on-error: false
    
    - name: Build AzureML Pipeline and Publish Endpoint
      run: bash -x ../../Resources/AzureML/cli/run-job.sh pipeline.yml
      working-directory: AzureML/TrainingPipeline
      
    - name: Remove IP of Github Runner from Storage Account
      if: always()
      run: bash whitelist-ip-remove.sh ${{ inputs.DEFAULTSTORAGE }} ${{ inputs.SUBSCRIPTION }} ${{ inputs.RESOURCEGROUP }} ${{ inputs.REPOPATH }}
      working-directory: Resources/AzureML/cli
      continue-on-error: false
      
